name = "gtd-app"
main = "src/worker.ts"
compatibility_date = "2025-01-10"

# Build configuration
[build]
command = "bun run build && bun run build:worker"

[[durable_objects.bindings]]
name = "USER_DO"
class_name = "UserDO"

[[durable_objects.bindings]]
name = "QUEUE_DO"
class_name = "QueueDO"

[[migrations]]
tag = "2025-10-20-cloudflare-do"
new_classes = ["UserDO", "QueueDO"]

# Workers Static Assets configuration
[assets]
directory = "dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

# Run Worker first for API routes (ensures API routes are processed before static assets)
run_worker_first = ["/api/*"]

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

# Environment variables for local/default
[vars]
AUTH_URL = "http://localhost:8787"

[env.dev]
name = "gtd-app-dev"
vars = { AUTH_URL = "https://auth-service-dev.christopher-esplin.workers.dev" }

[[env.dev.services]]
binding = "AUTH_SERVICE"
service = "auth-service-dev"

[env.production]
name = "gtd-app-prod"
vars = { AUTH_URL = "https://auth-service-prod.christopher-esplin.workers.dev" }

[[env.production.services]]
binding = "AUTH_SERVICE"
service = "auth-service-prod"
