name = "gtd-app"
main = "src/worker.ts"
compatibility_date = "2025-01-10"

# Workers Static Assets configuration
[assets]
directory = "dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

# Run Worker first for API routes
run_worker_first = ["/api/*"]

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

# Environment variables
# AUTH_URL - Auth service URL (set via wrangler secret or dashboard)
[vars]
AUTH_URL = "http://localhost:8787" # Default for local dev


[env.dev]
name = "gtd-app-dev"
vars = { AUTH_URL = "https://auth-service-dev.christopher-esplin.workers.dev" }

[env.production]
name = "gtd-app-prod"
# AUTH_URL should be set via: wrangler secret put AUTH_URL --env production
